apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ps-app-ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: ps-app-ui
    spec:
      containers:
      - name: ps-app-ui
        image: d066567/ps-app-ui:latest
        ports:
        - containerPort: 8000
