apiVersion: v1
kind: Service
metadata:
  name: ps-app-ui
  labels:
    run: ps-app-uiii
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80000
    protocol: TCP
  selector:
    run: ps-app-ui
