apiVersion: v1
kind: Service
metadata:
  name: ps-app-ui
  labels:
    run: ps-app-ui
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    run: ps-app-ui
