apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ps-ingress.bar.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ps-app-ui
          servicePort: 8000
      - path: /bar
        backend:
          serviceName: ps-app-svc
          servicePort: 3000
