apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  name: ps-ingress-1
spec:
  rules:
  - http:
      paths:
      - path: "/ps/config/"
        backend:
          serviceName: ps-config
          servicePort: 3300 
