apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ps-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: ps.app.storage
    http:
      paths:
      - path: /
        backend:
          serviceName: ps-config
          servicePort: 3300
      - path: /config
        backend:
          serviceName: ps-config
          servicePort: 3300
