apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ps-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ps-static-ip
spec:
  backend:
    serviceName: ps-app-ui
    servicePort: 8000
