apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ps-config
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: ps-config
    spec:
      containers:
      - name: ps-config-access
        image: d066567/psconfigaccesssvc:latest
        ports:
        - containerPort: 3100
      - name: ps-config-storage
        image: d066567/psconfigstoragesvc:latest
        ports:
        - containerPort: 3300
---
apiVersion: v1
kind: Service
metadata:
  name: ps-config
  labels:
    run: ps-configcd 
spec:
  type: ClusterIP
  ports:
  - name: ps-config-access
    port: 3100
    targetPort: 3100
  selector:
    run: ps-config
